import type { FoodManufacturingCase } from "./food-manufacturing-types";

export const sampleFoodManufacturingCases: FoodManufacturingCase[] = [
  {
    id: "sample-001",
    businessName: "농업회사법인(유)옹동",
    foodType: "주류",
    dispositionType: "품목제조정지",
    violation: "탁주 2종을 생산·판매하면서 자가품질검사를 장기간 실시하지 않은 사실이 확인됨",
    dispositionDetail: "품목제조정지 30일",
    dispositionDate: "2026-05-26",
    licenseNo: "20130019219",
    industryName: "식품제조가공업(주류)",
    address: "전북특별자치도 정읍시 옹동면 정동길 14-10",
    jurisdiction: "광주청",
    law: "식품위생법 제31조"
  },
  {
    id: "sample-002",
    businessName: "(주)정담푸드",
    foodType: "액상차",
    dispositionType: "영업정지",
    violation: "액상차 제품에 사용금지된 식품첨가물이 함유되지 않았다는 내용을 강조하여 표시·광고함",
    dispositionDetail: "영업정지",
    dispositionDate: "2026-05-22",
    licenseNo: "20180355577",
    industryName: "식품제조가공업",
    address: "경기도 화성시 봉담읍 전원길 42",
    jurisdiction: "경기도 화성시",
    law: "식품 등의 표시·광고에 관한 법률 제8조"
  },
  {
    id: "sample-003",
    businessName: "(주)베오베",
    foodType: "커피",
    dispositionType: "품목제조정지",
    violation: "커피 제품에서 금속 이물이 혼입된 사실이 확인됨",
    dispositionDetail: "품목제조정지, 해당제품 폐기",
    dispositionDate: "2026-05-20",
    licenseNo: "20170347016",
    industryName: "식품제조가공업",
    address: "경기도 용인시 처인구 모현읍 초부로148번길 1-3",
    jurisdiction: "경기도 용인시",
    law: "식품위생법 제7조"
  },
  {
    id: "sample-004",
    businessName: "(주)누리지에프에스",
    foodType: "음료베이스",
    dispositionType: "영업정지",
    violation: "음료베이스에 허용되지 않은 보존료를 사용하여 제조·판매함",
    dispositionDetail: "영업정지",
    dispositionDate: "2026-05-11",
    licenseNo: "20200363209",
    industryName: "식품제조가공업",
    address: "경기도 용인시 처인구 모현읍 곡현로 506",
    jurisdiction: "경기도 용인시",
    law: "식품위생법 제7조"
  },
  {
    id: "sample-005",
    businessName: "농업회사법인(주)미카129",
    foodType: "곡류가공품",
    dispositionType: "품목제조정지",
    violation: "곡류가공품 자가품질검사를 실시하지 않음",
    dispositionDetail: "품목제조정지",
    dispositionDate: "2026-05-20",
    licenseNo: "20220731021",
    industryName: "식품제조가공업",
    address: "전라남도 곡성군 옥과면 죽림5길 39",
    jurisdiction: "전라남도 곡성군",
    law: "식품위생법 제31조"
  },
  {
    id: "sample-006",
    businessName: "(주)파프리카",
    foodType: "기타가공품",
    dispositionType: "품목제조정지",
    violation: "기타가공품 일부 품목에 대해 자가품질검사 전 항목을 실시하지 않음",
    dispositionDetail: "품목제조정지",
    dispositionDate: "2026-04-27",
    licenseNo: "20230486438",
    industryName: "식품제조가공업",
    address: "경기도 광주시 광남안로 72-6",
    jurisdiction: "경기도 광주시",
    law: "식품위생법 제31조"
  },
  {
    id: "sample-007",
    businessName: "농업회사법인주식회사초정",
    foodType: "복합조미식품",
    dispositionType: "품목제조정지",
    violation: "복합조미식품 등 여러 식품유형에 대해 자가품질검사를 실시하지 않음",
    dispositionDetail: "품목제조정지",
    dispositionDate: "2026-05-20",
    licenseNo: "20140520058",
    industryName: "식품제조가공업",
    address: "전라남도 곡성군 옥과면 대학로 78-21",
    jurisdiction: "전라남도 곡성군",
    law: "식품위생법 제31조"
  },
  {
    id: "sample-008",
    businessName: "에이원식품",
    foodType: "초콜릿가공품",
    dispositionType: "품목제조정지",
    violation: "초콜릿가공품에 알레르기 유발물질인 밀을 표시하지 않음",
    dispositionDetail: "품목제조정지 15일",
    dispositionDate: "2026-05-19",
    licenseNo: "19940607175",
    industryName: "식품제조가공업",
    address: "경상남도 김해시 상동면 상동로685번안길 29-1",
    jurisdiction: "경상남도 김해시",
    law: "식품 등의 표시·광고에 관한 법률 제4조"
  },
  {
    id: "sample-009",
    businessName: "청오건강 농업회사법인주식회사 6공장",
    foodType: "땅콩 또는 견과류가공품",
    dispositionType: "품목류제조정지",
    violation: "볶음땅콩 제품의 총 아플라톡신 기준규격 부적합이 확인됨",
    dispositionDetail: "해당 제품 및 원료 폐기와 품목류제조정지",
    dispositionDate: "2026-05-12",
    licenseNo: "20160368513",
    industryName: "식품제조가공업",
    address: "경기도 광주시 도척면 도척로584번길 27",
    jurisdiction: "경기도 광주시",
    law: "식품위생법 제7조"
  },
  {
    id: "sample-010",
    businessName: "(주)씨큐브",
    foodType: "기타가공품",
    dispositionType: "영업허가·등록취소",
    violation: "영업시설의 전부를 철거한 사실이 확인됨",
    dispositionDetail: "영업허가·등록취소",
    dispositionDate: "2026-05-14",
    licenseNo: "20100329042",
    industryName: "식품제조가공업",
    address: "경기도 과천시 삼부골2로 20",
    jurisdiction: "경기도 과천시",
    law: "식품위생법 제37조"
  },
  {
    id: "sample-011",
    businessName: "(주)스타미트팜",
    foodType: "기타가공품",
    dispositionType: "영업소폐쇄",
    violation: "영업시설물 멸실이 확인됨",
    dispositionDetail: "영업소폐쇄",
    dispositionDate: "2026-04-28",
    licenseNo: "20200349240",
    industryName: "식품제조가공업",
    address: "경기도 남양주시 진접읍 양진로1002번길 8-21",
    jurisdiction: "경기도 남양주시",
    law: "식품위생법 제75조"
  }
];
